pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t my-react-app - < ./jenkins/Dockerfile.build > log_build.txt'
            }
            post {
                always {
                    archiveArtifacts(artifacts: 'log_*.txt', fingerprint: true, followSymlinks: false)
                }
                success {
                    echo 'Build success'
                }
                failure {
                    echo 'Build failed'
                } 
            }
        }
        stage('Test') { 
            steps {
                sh 'docker build -t my-react-app - < ./jenkins/Dockerfile.test > log_test.txt'
            }
            post {
                always {
                    archiveArtifacts(artifacts: 'log_*.txt', fingerprint: true, followSymlinks: false)
                }
                success {
                    echo 'Test success'
                }
                failure {
                    echo 'Test failed'
                } 
            }
        }

        stage('Deploy') { 
            steps {
                sh 'docker build -t my-react-app - < ./jenkins/Dockerfile.deploy > log_deploy.txt'
            }
            post {
                always {
                    archiveArtifacts(artifacts: 'log_*.txt', fingerprint: true, followSymlinks: false)
                }
                success {
                    sh "docker save my-react-app -o my-react-app.tar"
                    echo 'Deploy success'
                }
                failure {
                    echo 'Deploy failed'
                } 
            }
        }
    }
}